### ISSUE TITLE
start of ndnpingserver failed

### ISSUE THREAD

**Issue by jiachenwang** [named-data/ndn-tlv-ping#10]
I followed the instruction and installed ndn-cxx, NFD and ndn-tlv-ping on Ubuntu 14.04.

Usage on https://github.com/named-data/ndn-tlv-ping says: "ndnpingserver /test/pingserver",
while "ndnpingserver -h" shows " Usage: ndnpingserver ndn:/name/prefix [options] Starts a NDN ping server that responds to Interests with name ndn:/name/prefix/ping/number."

I tried these: "ndnpingserver ndn:/w/n2u/qwer/1", "ndnpingserver /w/n2u/qwer/1", " ndnpingserver /test/pingserver" and "ndnpingserver ndn:/test/pingserver".
All told me error like this: 

"=== Ping Server /w/n2u/qwer/1 ===

ndnpingserver: symbol lookup error: ndnpingserver: undefined symbol: _ZN3ndn5Block9push_backERKS0_"

Where is it wrong? How to solve this?

**Comment by cawka** [comment]
Most likely, you have multiple versions of ndn-cxx library installed on your system.  Make sure you have exactly one version installed (e.g., only in /usr or only in /usr/local).

**Comment by jiachenwang** [comment]
Yes, indeed. I moved the ndn bin from /use/local/bin to ~/ndn and type absolute path when pinging. The problem been solved. Thank you!
