### ISSUE TITLE
Deprecate ndn-tlv-ping

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndn-tlv-ping#9]
Deprecate ndn-tlv-ping repository, and refer users to [ndn-tools](https://github.com/named-data/ndn-tools).

**Comment by eric135** [comment]
Should a message also be displayed by ndn-tlv-ping, similar to http://redmine.named-data.net/issues/2817?

**Comment by yoursunny** [comment]
No notice message is necessary.

Unlike `ndn-tlv-peek` whose replacement is `ndnpeek`, the executable name for `ndnping' hasn't changed.
`ndnping` from ndn-tlv-ping and the counterpart from ndn-tools cannot coexist.

**Comment by yoursunny** [comment]
This issue is not blocked and can start now.

Suggested actions:
1. modify `README.md`: provide a link to ndn-tools GitHub repository
2. update GitHub repository description to say ndn-tlv-ping is deprecated

**Comment by eric135** [comment]
I will work on this issue.
